"""Add likes table and relationships

Revision ID: 803b30f4fa25
Revises: daa6ffd0a5b2
Create Date: 2025-10-11 01:07:03.269391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803b30f4fa25'
down_revision: Union[str, Sequence[str], None] = 'daa6ffd0a5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
